[project]
name = "spycewar"
version = "1.0.2"
description = "A game inspired by Spacewar!"
authors = [{ name = "Daniel Marín" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["pygame", "pre-commit", "rich>=14.0.0"]

[tool.setuptools.packages.find]
include = ["spycewar", "config"]

[project.scripts]
spycewar = "spycewar:main"
