[project]
name = "spycewar"
version = "1.2.0"
description = "A game inspired by Spacewar!"
authors = [{ name = "Daniel Marín" }]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "rich>=14.2.0",
]

[tool.setuptools.packages.find]
include = ["spycewar", "config"]

[project.scripts]
spycewar = "spycewar:main"
