"""Module for the constants used in the game."""

GAME_NAME = "SPYCEWAR!"
GAME_OVER = "GAME OVER"
SCREEN_WIDTH_ENV_VAR = "SPYWARE_SCREEN_WIDTH"
SCREEN_HEIGHT_ENV_VAR = "SPYWARE_SCREEN_HEIGHT"
SPYCEWAR_BLUE = (78, 216, 253)
